<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CoaStructureSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();
        
        // Clear existing COA data
        DB::table('coas')->delete();
        
        // Header Accounts (Induk)
        $headers = [
            [
                'kode_akun' => '1100',
                'nama_akun' => 'Kas dan Bank',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Aktiva Lancar',
                'is_akun_header' => 1,
                'kode_induk' => null,
                'saldo_normal' => 'debit',
                'saldo_awal' => 0,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Header untuk kas dan bank',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '1200',
                'nama_akun' => 'Aktiva Tetap',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Aktiva Tetap',
                'is_akun_header' => 1,
                'kode_induk' => null,
                'saldo_normal' => 'debit',
                'saldo_awal' => 0,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Header untuk aktiva tetap',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '2100',
                'nama_akun' => 'Kewajiban Jangka Pendek',
                'tipe_akun' => 'Liability',
                'kategori_akun' => 'Kewajiban Jangka Pendek',
                'is_akun_header' => 1,
                'kode_induk' => null,
                'saldo_normal' => 'kredit',
                'saldo_awal' => 0,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Header untuk kewajiban jangka pendek',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '3100',
                'nama_akun' => 'Modal',
                'tipe_akun' => 'Equity',
                'kategori_akun' => 'Modal',
                'is_akun_header' => 1,
                'kode_induk' => null,
                'saldo_normal' => 'kredit',
                'saldo_awal' => 0,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Header untuk modal',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '4100',
                'nama_akun' => 'Pendapatan Usaha',
                'tipe_akun' => 'Revenue',
                'kategori_akun' => 'Pendapatan Usaha',
                'is_akun_header' => 1,
                'kode_induk' => null,
                'saldo_normal' => 'kredit',
                'saldo_awal' => 0,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Header untuk pendapatan usaha',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '5100', // Header untuk expense sesuai permintaan
                'nama_akun' => 'Beban',
                'tipe_akun' => 'Expense',
                'kategori_akun' => 'Beban Usaha',
                'is_akun_header' => 1,
                'kode_induk' => null,
                'saldo_normal' => 'debit',
                'saldo_awal' => 0,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Header untuk semua beban usaha',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        // Detail Accounts
        $details = [
            // Kas dan Bank
            [
                'kode_akun' => '1101',
                'nama_akun' => 'Kas',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Aktiva Lancar',
                'is_akun_header' => 0,
                'kode_induk' => '1100',
                'saldo_normal' => 'debit',
                'saldo_awal' => 75000000.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Kas kecil untuk keperluan operasional harian secara tunai',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '1102',
                'nama_akun' => 'Kas di Bank',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Aktiva Lancar',
                'is_akun_header' => 0,
                'kode_induk' => '1100',
                'saldo_normal' => 'debit',
                'saldo_awal' => 100000000.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Saldo rekening bank utama perusahaan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '1103',
                'nama_akun' => 'Piutang Usaha',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Aktiva Lancar',
                'is_akun_header' => 0,
                'kode_induk' => '1100',
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Piutang kepada pelanggan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '1105',
                'nama_akun' => 'Persediaan Barang Dalam Proses',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Aktiva Lancar',
                'is_akun_header' => 0,
                'kode_induk' => '1100',
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Barang yang masih dalam proses produksi',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '1106',
                'nama_akun' => 'Persediaan Barang Jadi',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Aktiva Lancar',
                'is_akun_header' => 0,
                'kode_induk' => '1100',
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Barang jadi siap dijual',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '1130',
                'nama_akun' => 'PPN Masukan',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Aktiva Lancar',
                'is_akun_header' => 0,
                'kode_induk' => '1100',
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'PPN yang dapat dikreditkan',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Persediaan Bahan Baku (Header)
            [
                'kode_akun' => '122122',
                'nama_akun' => 'Persediaan Bahan Baku',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Aktiva Lancar',
                'is_akun_header' => 1,
                'kode_induk' => '1100',
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Header untuk persediaan bahan baku',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '122123',
                'nama_akun' => 'Persediaan Ayam Potong',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Aktiva Lancar',
                'is_akun_header' => 0,
                'kode_induk' => '122122',
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Persediaan ayam potong',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '122124',
                'nama_akun' => 'Persediaan Ayam Kampung',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Aktiva Lancar',
                'is_akun_header' => 0,
                'kode_induk' => '122122',
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Persediaan ayam kampung',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '122125',
                'nama_akun' => 'Persediaan Bebek',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Aktiva Lancar',
                'is_akun_header' => 0,
                'kode_induk' => '122122',
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Persediaan bebek',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Persediaan Bahan Pendukung (Header)
            [
                'kode_akun' => '1107',
                'nama_akun' => 'Persediaan Bahan Pendukung',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Aktiva Lancar',
                'is_akun_header' => 1,
                'kode_induk' => '1100',
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Header untuk persediaan bahan pendukung',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '122111',
                'nama_akun' => 'Persediaan Air',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Persediaan Bahan Pendukung',
                'is_akun_header' => 0,
                'kode_induk' => '1107',
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Persediaan air',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '122112',
                'nama_akun' => 'Persediaan Minyak Goreng',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Persediaan Bahan Pendukung',
                'is_akun_header' => 0,
                'kode_induk' => '1107',
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Persediaan minyak goreng',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '122113',
                'nama_akun' => 'Persediaan Gas',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Persediaan Bahan Pendukung',
                'is_akun_header' => 0,
                'kode_induk' => '1107',
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Persediaan gas',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '122114',
                'nama_akun' => 'Persediaan Ketumbar',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Persediaan Bahan Pendukung',
                'is_akun_header' => 0,
                'kode_induk' => '1107',
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Persediaan ketumbar',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '122115',
                'nama_akun' => 'Persediaan Cabe Merah',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Persediaan Bahan Pendukung',
                'is_akun_header' => 0,
                'kode_induk' => '1107',
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Persediaan cabe merah',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '122116',
                'nama_akun' => 'Persediaan Bawang Putih',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Persediaan Bahan Pendukung',
                'is_akun_header' => 0,
                'kode_induk' => '1107',
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Persediaan bawang putih',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '122117',
                'nama_akun' => 'Persediaan Tepung Maizena',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Persediaan Bahan Pendukung',
                'is_akun_header' => 0,
                'kode_induk' => '1107',
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Persediaan tepung maizena',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '122118',
                'nama_akun' => 'Persediaan Merica Bubuk',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Persediaan Bahan Pendukung',
                'is_akun_header' => 0,
                'kode_induk' => '1107',
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Persediaan merica bubuk',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '122119',
                'nama_akun' => 'Persediaan Listrik',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Persediaan Bahan Pendukung',
                'is_akun_header' => 0,
                'kode_induk' => '1107',
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Persediaan listrik',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '122120',
                'nama_akun' => 'Persediaan Bawang Merah',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Persediaan Bahan Pendukung',
                'is_akun_header' => 0,
                'kode_induk' => '1107',
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Persediaan bawang merah',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '122121',
                'nama_akun' => 'Persediaan Kemasan',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Persediaan Bahan Pendukung',
                'is_akun_header' => 0,
                'kode_induk' => '1107',
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Persediaan kemasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '122126',
                'nama_akun' => 'Persediaan Lada Hitam',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Persediaan Bahan Pendukung',
                'is_akun_header' => 0,
                'kode_induk' => '1107',
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Persediaan lada hitam',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Aktiva Tetap
            [
                'kode_akun' => '1201',
                'nama_akun' => 'Tanah',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Aktiva Tetap',
                'is_akun_header' => 0,
                'kode_induk' => '1200',
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Tanah milik perusahaan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '1202',
                'nama_akun' => 'Gedung',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Aktiva Tetap',
                'is_akun_header' => 0,
                'kode_induk' => '1200',
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Gedung dan bangunan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '120201',
                'nama_akun' => 'Akumulasi Penyusutan Gedung',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Aktiva Tetap',
                'is_akun_header' => 0,
                'kode_induk' => '1200',
                'saldo_normal' => 'kredit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Akumulasi penyusutan gedung',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '1203',
                'nama_akun' => 'Kendaraan',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Aktiva Tetap',
                'is_akun_header' => 0,
                'kode_induk' => '1200',
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Kendaraan operasional perusahaan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '120301',
                'nama_akun' => 'Akumulasi Penyusutan Kendaraan',
                'tipe_akun' => 'Asset',
                'kategori_akun' => 'Aktiva Tetap',
                'is_akun_header' => 0,
                'kode_induk' => '1200',
                'saldo_normal' => 'kredit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Akumulasi penyusutan kendaraan',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Kewajiban
            [
                'kode_akun' => '2101',
                'nama_akun' => 'Hutang Usaha',
                'tipe_akun' => 'Liability',
                'kategori_akun' => 'Kewajiban Jangka Pendek',
                'is_akun_header' => 0,
                'kode_induk' => '2100',
                'saldo_normal' => 'kredit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Hutang kepada supplier',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '2102',
                'nama_akun' => 'Hutang Pajak',
                'tipe_akun' => 'Liability',
                'kategori_akun' => 'Kewajiban Jangka Pendek',
                'is_akun_header' => 0,
                'kode_induk' => '2100',
                'saldo_normal' => 'kredit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Hutang pajak yang belum disetor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '2110',
                'nama_akun' => 'Utang Penjualan',
                'tipe_akun' => 'Liability',
                'kategori_akun' => 'Kewajiban Lancar',
                'is_akun_header' => 0,
                'kode_induk' => '2100',
                'saldo_normal' => 'kredit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Utang penjualan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '2111',
                'nama_akun' => 'Utang Gaji',
                'tipe_akun' => 'Liability',
                'kategori_akun' => 'Kewajiban Lancar',
                'is_akun_header' => 0,
                'kode_induk' => '2100',
                'saldo_normal' => 'kredit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Utang gaji karyawan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '2120',
                'nama_akun' => 'Utang Pajak',
                'tipe_akun' => 'Liability',
                'kategori_akun' => 'Kewajiban Lancar',
                'is_akun_header' => 0,
                'kode_induk' => '2100',
                'saldo_normal' => 'kredit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Utang pajak',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Modal
            [
                'kode_akun' => '3101',
                'nama_akun' => 'Modal Saham',
                'tipe_akun' => 'Equity',
                'kategori_akun' => 'Modal',
                'is_akun_header' => 0,
                'kode_induk' => '3100',
                'saldo_normal' => 'kredit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Modal disetor pemegang saham',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '3102',
                'nama_akun' => 'Laba Ditahan',
                'tipe_akun' => 'Equity',
                'kategori_akun' => 'Modal',
                'is_akun_header' => 0,
                'kode_induk' => '3100',
                'saldo_normal' => 'kredit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Akumulasi laba yang ditahan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '3110',
                'nama_akun' => 'Modal',
                'tipe_akun' => 'Equity',
                'kategori_akun' => 'Modal',
                'is_akun_header' => 0,
                'kode_induk' => '3100',
                'saldo_normal' => 'kredit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Modal perusahaan',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Pendapatan
            [
                'kode_akun' => '4101',
                'nama_akun' => 'Penjualan Produk',
                'tipe_akun' => 'Revenue',
                'kategori_akun' => 'Pendapatan Usaha',
                'is_akun_header' => 0,
                'kode_induk' => '4100',
                'saldo_normal' => 'kredit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Pendapatan dari penjualan produk',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '4110',
                'nama_akun' => 'Pendapatan Penjualan',
                'tipe_akun' => 'Revenue',
                'kategori_akun' => 'Pendapatan',
                'is_akun_header' => 0,
                'kode_induk' => '4100',
                'saldo_normal' => 'kredit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Pendapatan penjualan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '4120',
                'nama_akun' => 'Retur Penjualan',
                'tipe_akun' => 'Revenue',
                'kategori_akun' => 'Pendapatan',
                'is_akun_header' => 0,
                'kode_induk' => '4100',
                'saldo_normal' => 'debit', // Retur penjualan saldo normalnya debit
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Retur penjualan',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Beban (dengan header 5100 sesuai permintaan)
            [
                'kode_akun' => '5101',
                'nama_akun' => 'Beban Gaji Karyawan',
                'tipe_akun' => 'Expense',
                'kategori_akun' => 'Beban Usaha',
                'is_akun_header' => 0,
                'kode_induk' => '5100', // Mengarah ke header 5100
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Beban gaji dan tunjangan karyawan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '5102',
                'nama_akun' => 'Beban Listrik dan Air',
                'tipe_akun' => 'Expense',
                'kategori_akun' => 'Beban Usaha',
                'is_akun_header' => 0,
                'kode_induk' => '5100', // Mengarah ke header 5100
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Beban listrik dan air kantor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '5110',
                'nama_akun' => 'Beban Gaji',
                'tipe_akun' => 'Expense',
                'kategori_akun' => 'Beban Usaha',
                'is_akun_header' => 0,
                'kode_induk' => '5100', // Mengarah ke header 5100
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Beban gaji',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '5120',
                'nama_akun' => 'Beban Pajak',
                'tipe_akun' => 'Expense',
                'kategori_akun' => 'Beban Usaha',
                'is_akun_header' => 0,
                'kode_induk' => '5100', // Mengarah ke header 5100
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Beban pajak',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '5130',
                'nama_akun' => 'Beban Sewa',
                'tipe_akun' => 'Expense',
                'kategori_akun' => 'Beban Usaha',
                'is_akun_header' => 0,
                'kode_induk' => '5100', // Mengarah ke header 5100
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Beban sewa',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_akun' => '5140',
                'nama_akun' => 'Beban Listrik',
                'tipe_akun' => 'Expense',
                'kategori_akun' => 'Beban Usaha',
                'is_akun_header' => 0,
                'kode_induk' => '5100', // Mengarah ke header 5100
                'saldo_normal' => 'debit',
                'saldo_awal' => 0.00,
                'tanggal_saldo_awal' => '2026-03-01',
                'posted_saldo_awal' => 0,
                'keterangan' => 'Beban listrik',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        // Insert headers first
        DB::table('coas')->insert($headers);
        
        // Insert details
        DB::table('coas')->insert($details);

        $this->command->info('✅ COA Structure seeded successfully!');
        $this->command->info('📊 Total accounts: ' . (count($headers) + count($details)));
        $this->command->info('🏗️ Header accounts: ' . count($headers));
        $this->command->info('📝 Detail accounts: ' . count($details));
        $this->command->info('📋 Expense header (5100) created as requested!');
    }
}
