<?php
require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use Illuminate\Support\Facades\DB;

// Hapus entry JU yang tergenerate dari tombol Posting (AsetController)
// referensi dari AsetController biasanya format: 'ASET-1' atau 'DEPR-ASET-1'
// referensi dari Bulk (JurnalPenyesuaianAsetController) format: 'ASET-1-2023-01'

$entries = DB::table('jurnal_umum')
    ->where('tipe_referensi', 'adjustment_depreciation')
    ->get();

$count = 0;
foreach($entries as $entry) {
    // Check if it's generated by individual button
    // It doesn't have the year-month suffix like '-2023-01'
    if (preg_match('/^ASET-\d+$/', $entry->referensi) || preg_match('/^DEPR-ASET-\d+$/', $entry->referensi)) {
        DB::table('jurnal_umum')->where('id', $entry->id)->delete();
        $count++;
    }
}

echo "Berhasil menghapus $count entry dari tabel jurnal_umum.\n";
