-- Import Data COA
-- File ini akan mengimpor data Chart of Accounts (COA) ke database
-- Pastikan tabel coas sudah ada sebelum menjalankan script ini

-- Hapus data lama untuk company_id = 1 (uncomment jika ingin reset total)
-- DELETE FROM coas WHERE company_id = 1;
-- ALTER TABLE coas AUTO_INCREMENT = 1;

-- Atau hapus hanya yang akan diimport ulang
DELETE FROM coas WHERE company_id = 1 AND id BETWEEN 1 AND 95;

-- Insert data COA
INSERT INTO `coas` (`id`, `kode_akun`, `nama_akun`, `tipe_akun`, `kategori_akun`, `is_akun_header`, `kode_induk`, `saldo_normal`, `saldo_awal`, `tanggal_saldo_awal`, `posted_saldo_awal`, `keterangan`, `created_at`, `updated_at`, `company_id`) VALUES
(1, '11', 'Aset', 'Aset', 'Aset', 1, NULL, 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(2, '111', 'Kas Bank', 'Aset', 'Aset Lancar', 0, '11', 'debit', 100000000.00, NULL, 0, NULL, NOW(), NOW(), 1),
(3, '112', 'Kas', 'Aset', 'Aset Lancar', 0, '11', 'debit', 75000000.00, NULL, 0, NULL, NOW(), NOW(), 1),
(4, '113', 'Kas Kecil', 'Aset', 'Aset Lancar', 0, '11', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(5, '114', 'Pers. Bahan Baku', 'Aset', 'Aset Lancar', 1, '11', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(6, '1141', 'Pers. Bahan Baku Jagung', 'Aset', 'Aset Lancar', 0, '114', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(7, '115', 'Pers. Bahan Pendukung', 'Aset', 'Aset Lancar', 1, '11', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(8, '1151', 'Pers. Bahan Pendukung Susu', 'Aset', 'Aset Lancar', 0, '115', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(9, '1152', 'Pers. Bahan Pendukung Keju', 'Aset', 'Aset Lancar', 0, '115', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(10, '1153', 'Pers. Bahan Pendukung Kemasan (Cup)', 'Aset', 'Aset Lancar', 0, '115', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(11, '116', 'Pers. Barang Jadi', 'Aset', 'Aset Lancar', 1, '11', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(12, '1161', 'Pers. Barang Jadi Jasuke', 'Aset', 'Aset Lancar', 0, '116', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(13, '117', 'Pers. Barang dalam Proses', 'Aset', 'Aset Lancar', 0, '11', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(14, '118', 'Piutang', 'Aset', 'Aset Lancar', 0, '11', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(15, '119', 'Peralatan', 'Aset', 'Aset Tidak Lancar', 0, '11', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(16, '120', 'Akumulasi Penyusutan Peralatan', 'Aset', 'Aset Tidak Lancar', 0, '11', 'kredit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(17, '125', 'Mesin', 'Aset', 'Aset Tidak Lancar', 0, '11', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(18, '126', 'Akumulasi Penyusutan Mesin', 'Aset', 'Aset Tidak Lancar', 0, '11', 'kredit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(19, '21', 'Hutang', 'Kewajiban', 'Kewajiban', 1, NULL, 'kredit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(20, '210', 'Hutang Usaha', 'Kewajiban', 'Kewajiban Jangka Pendek', 0, '21', 'kredit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(21, '211', 'Hutang Gaji', 'Kewajiban', 'Kewajiban Jangka Pendek', 0, '21', 'kredit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(22, '31', 'Modal', 'Modal', 'Modal', 1, NULL, 'kredit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(23, '310', 'Modal Usaha', 'Modal', 'Modal', 0, '31', 'kredit', 264450000.00, NULL, 0, NULL, NOW(), NOW(), 1),
(24, '311', 'Prive', 'Modal', 'Modal', 0, '31', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(25, '41', 'Penjualan', 'Pendapatan', 'Pendapatan', 1, NULL, 'kredit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(26, '410', 'Penjualan - Jasuke', 'Pendapatan', 'Pendapatan', 0, '41', 'kredit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(27, '42', 'Retur Penjualan', 'Pendapatan', 'Pendapatan', 0, NULL, 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(28, '51', 'BBB - Biaya Bahan Baku', 'Biaya Bahan Baku', 'Biaya Produksi', 1, NULL, 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(29, '510', 'BBB - Jagung', 'Biaya Bahan Baku', 'Biaya Produksi', 0, '51', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(30, '52', 'BTKL', 'Biaya Tenaga Kerja Langsung', 'Biaya Produksi', 1, NULL, 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(31, '520', 'BTKL - Produksi Jasuke', 'Biaya Tenaga Kerja Langsung', 'Biaya Produksi', 0, '52', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(32, '53', 'BOP', 'Biaya Overhead Pabrik', 'Biaya Produksi', 1, NULL, 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(33, '530', 'BOP - Susu', 'Biaya Overhead Pabrik', 'Biaya Produksi', 0, '53', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(34, '531', 'BOP - Keju', 'Biaya Overhead Pabrik', 'Biaya Produksi', 0, '53', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(35, '532', 'BOP - Kemasan', 'Biaya Overhead Pabrik', 'Biaya Produksi', 0, '53', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(36, '55', 'BOP Lain', 'BOP Tidak Langsung Lainnya', 'Biaya Produksi', 1, NULL, 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(37, '550', 'BOP - Listrik', 'BOP Tidak Langsung Lainnya', 'Biaya Produksi', 0, '55', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(38, '551', 'BOP - Sewa Tempat', 'BOP Tidak Langsung Lainnya', 'Biaya Produksi', 0, '55', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(39, '552', 'BOP - Penyusutan Gedung', 'BOP Tidak Langsung Lainnya', 'Biaya Produksi', 0, '55', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(40, '553', 'BOP - Penyusutan Peralatan', 'BOP Tidak Langsung Lainnya', 'Biaya Produksi', 0, '55', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(41, '121', 'Gedung', 'Aset', 'Aset Tidak Lancar', 0, '11', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(42, '122', 'Akumulasi Penyusutan Gedung', 'Aset', 'Aset Tidak Lancar', 0, '11', 'kredit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(43, '123', 'Kendaraan', 'Aset', 'Aset Tidak Lancar', 0, '11', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(44, '124', 'Akumulasi Penyusutan Kendaraan', 'Aset', 'Aset Tidak Lancar', 0, '11', 'kredit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(45, '127', 'PPN Masukan', 'Aset', 'Aset Lancar', 0, '11', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(46, '212', 'PPN Keluaran', 'Kewajiban', 'Kewajiban Jangka Pendek', 0, '21', 'kredit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(47, '312', 'Laba Ditahan', 'Modal', 'Modal', 0, '31', 'kredit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(48, '43', 'Pendapatan Ongkir', 'Pendapatan', 'Pendapatan', 0, NULL, 'kredit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(49, '54', 'BTKTL', 'Biaya Tenaga Kerja Tidak Langsung', 'Biaya Produksi', 1, NULL, 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(50, '540', 'BTKTL - Pegawai Pemasaran', 'Biaya Tenaga Kerja Tidak Langsung', 'Biaya Produksi', 0, '54', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(51, '541', 'BTKTL - Pegawai Kemasan', 'Biaya Tenaga Kerja Tidak Langsung', 'Biaya Produksi', 0, '54', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(52, '554', 'BOP - Penyusutan Kendaraan', 'BOP Tidak Langsung Lainnya', 'Biaya Produksi', 0, '55', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(53, '555', 'BOP - Penyusutan Mesin', 'BOP Tidak Langsung Lainnya', 'Biaya Produksi', 0, '55', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(54, '556', 'BOP - Air Tambahan', 'BOP Tidak Langsung Lainnya', 'Biaya Produksi', 0, '55', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(55, '557', 'BOP - Lainnya', 'BOP Tidak Langsung Lainnya', 'Biaya Produksi', 0, '55', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(56, '1600', 'Harga Pokok Penjualan', 'Biaya Bahan Baku', 'HPP', 1, NULL, 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(57, '1601', 'HPP - Bahan Baku', 'Biaya Bahan Baku', 'HPP', 0, '1600', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(58, '1602', 'HPP - BTKL', 'Biaya Tenaga Kerja Langsung', 'HPP', 0, '1600', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(59, '1603', 'HPP - Overhead Pabrik', 'Biaya Overhead Pabrik', 'HPP', 0, '1600', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(60, '1142', 'Pers. Bahan Baku Ayam Potong', 'Aset', 'Aset Lancar', 0, '114', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(61, '1143', 'Pers. Bahan Baku Ayam Kampung', 'Aset', 'Aset Lancar', 0, '114', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(62, '1144', 'Pers. Bahan Baku Bebek', 'Aset', 'Aset Lancar', 0, '114', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(63, '1145', 'Pers. Bahan Baku Ayam Lainnya', 'Aset', 'Aset Lancar', 0, '114', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(64, '1150', 'Pers. Bahan Pendukung Air', 'Aset', 'Aset Lancar', 0, '115', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(65, '1154', 'Pers. Bahan Pendukung Minyak Goreng', 'Aset', 'Aset Lancar', 0, '115', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(66, '1155', 'Pers. Bahan Pendukung Tepung Terigu', 'Aset', 'Aset Lancar', 0, '115', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(67, '1156', 'Pers. Bahan Pendukung Tepung Maizena', 'Aset', 'Aset Lancar', 0, '115', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(68, '1157', 'Pers. Bahan Pendukung Lada', 'Aset', 'Aset Lancar', 0, '115', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(69, '1158', 'Pers. Bahan Pendukung Bubuk Kaldu', 'Aset', 'Aset Lancar', 0, '115', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(70, '1159', 'Pers. Bahan Pendukung Bubuk Bawang Putih', 'Aset', 'Aset Lancar', 0, '115', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(71, '1160', 'Pers. Bahan Pendukung Kemasan', 'Aset', 'Aset Lancar', 0, '115', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(72, '1162', 'Pers. Barang Jadi Ayam Crispy Macdi', 'Aset', 'Aset Lancar', 0, '116', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(73, '1163', 'Pers. Barang Jadi Ayam Goreng Bundo', 'Aset', 'Aset Lancar', 0, '116', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(74, '411', 'Penjualan - Ayam Crispy Macdi', 'Pendapatan', 'Pendapatan', 0, '41', 'kredit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(75, '412', 'Penjualan - Ayam Goreng Bundo', 'Pendapatan', 'Pendapatan', 0, '41', 'kredit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(76, '511', 'BBB - Ayam Potong', 'Biaya Bahan Baku', 'Biaya Produksi', 0, '51', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(77, '512', 'BBB - Ayam Kampung', 'Biaya Bahan Baku', 'Biaya Produksi', 0, '51', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(78, '513', 'BBB - Bebek', 'Biaya Bahan Baku', 'Biaya Produksi', 0, '51', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(79, '521', 'BTKL - Perbumbuan', 'Biaya Tenaga Kerja Langsung', 'Biaya Produksi', 0, '52', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(80, '522', 'BTKL - Penggorengan', 'Biaya Tenaga Kerja Langsung', 'Biaya Produksi', 0, '52', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(81, '523', 'BTKL - Pengemasan', 'Biaya Tenaga Kerja Langsung', 'Biaya Produksi', 0, '52', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(82, '533', 'BOP - Air', 'Biaya Overhead Pabrik', 'Biaya Produksi', 0, '53', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(83, '534', 'BOP - Minyak Goreng', 'Biaya Overhead Pabrik', 'Biaya Produksi', 0, '53', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(84, '535', 'BOP - Tepung Terigu', 'Biaya Overhead Pabrik', 'Biaya Produksi', 0, '53', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(85, '536', 'BOP - Tepung Maizena', 'Biaya Overhead Pabrik', 'Biaya Produksi', 0, '53', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(86, '537', 'BOP - Lada', 'Biaya Overhead Pabrik', 'Biaya Produksi', 0, '53', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(87, '538', 'BOP - Bubuk Kaldu', 'Biaya Overhead Pabrik', 'Biaya Produksi', 0, '53', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(88, '539', 'BOP - Bubuk Bawang Putih', 'Biaya Overhead Pabrik', 'Biaya Produksi', 0, '53', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(89, '542', 'BTKTL - Satpam Pabrik', 'Biaya Tenaga Kerja Tidak Langsung', 'Biaya Produksi', 0, '54', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(90, '543', 'BTKTL - Cleaning Service', 'Biaya Tenaga Kerja Tidak Langsung', 'Biaya Produksi', 0, '54', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(91, '544', 'BTKTL - Mandor', 'Biaya Tenaga Kerja Tidak Langsung', 'Biaya Produksi', 0, '54', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(92, '545', 'BTKTL - Pegawai Keuangan', 'Biaya Tenaga Kerja Tidak Langsung', 'Biaya Produksi', 0, '54', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(93, '546', 'BTKTL - Lainnya', 'Biaya Tenaga Kerja Tidak Langsung', 'Biaya Produksi', 0, '54', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(94, '558', 'Beban Transport Pembelian', 'BOP Tidak Langsung Lainnya', 'Biaya Produksi', 0, '55', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1),
(95, '559', 'Diskon Pembelian', 'BOP Tidak Langsung Lainnya', 'Biaya Produksi', 0, '55', 'debit', 0.00, NULL, 0, NULL, NOW(), NOW(), 1)
-- Selesai import
